
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default  # Specify the namespace where the secret will be created
type: Opaque  # Type of the secret
data:
  username: YWRtaW4=  # Base64 encoded value of the username
  password: cGFzc3dvcmQ=  # Base64 encoded value of the password

